In [1]:
import numpy as np
from scipy.linalg import hadamard

In [3]:
hadamard(4)

array([[ 1,  1,  1,  1],
       [ 1, -1,  1, -1],
       [ 1,  1, -1, -1],
       [ 1, -1, -1,  1]])

In [4]:
np.kron(hadamard(2), hadamard(2))

array([[ 1,  1,  1,  1],
       [ 1, -1,  1, -1],
       [ 1,  1, -1, -1],
       [ 1, -1, -1,  1]])

In [7]:
np.kron(hadamard(4), hadamard(4)) == hadamard(16)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  Tru

In [33]:
x = np.random.randn(4)
x_2 = np.outer(x, x).reshape(-1)
y = np.random.randn(4)
y_2 = np.outer(y, y).reshape(-1)

In [34]:
hadamard(16) @ x_2

array([13.50303374,  0.57762523, -3.188991  ,  6.1917616 ,  0.57762523,
        0.02470933, -0.13641688,  0.26486772, -3.188991  , -0.13641688,
        0.75313917, -1.46229895,  6.1917616 ,  0.26486772, -1.46229895,
        2.83920728])

In [35]:
hadamard(4) @ x

array([-3.67464743, -0.15719201,  0.86783591, -1.68499474])

In [36]:
np.outer(hadamard(4) @ x, hadamard(4) @ x).reshape(-1)

array([13.50303374,  0.57762523, -3.188991  ,  6.1917616 ,  0.57762523,
        0.02470933, -0.13641688,  0.26486772, -3.188991  , -0.13641688,
        0.75313917, -1.46229895,  6.1917616 ,  0.26486772, -1.46229895,
        2.83920728])

In [37]:
x_emb = np.fft.ifft(np.fft.fft(hadamard(4) @ x) * np.fft.fft(hadamard(4) @ x))
y_emb = np.fft.ifft(np.fft.fft(hadamard(4) @ y) * np.fft.fft(hadamard(4) @ y))

In [38]:
x_emb.dot(y_emb).real

76.27633791583226

In [39]:
(hadamard(16) @ x_2).dot(hadamard(16) @ y_2)

6.00539803610924